// This file is generated by `flutterfire configure`.
// Run the following command to generate it for your Firebase project:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//
// Until then, this stub satisfies the import so the project compiles.
// Replace with the real generated file before running on a device.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported in this app.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform: $defaultTargetPlatform');
    }
  }

  // Values sourced from android/app/google-services.json (project notesnexam-9041a).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLpukABnUHI53IymDI9xh3a6cLgg19ues',
    appId: '1:472698647575:android:b3f84000049bb4db141852',
    messagingSenderId: '472698647575',
    projectId: 'notesnexam-9041a',
    storageBucket: 'notesnexam-9041a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_BUCKET',
    iosBundleId: 'com.edutech.app',
  );
}
